---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  labels:
    app.kubernetes.io/name: "todo-backend"
    app.kubernetes.io/version: "1.0.0"
  name: "todo-backend"
---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app.kubernetes.io/name: "todo-backend"
    app.kubernetes.io/version: "1.0.0"
  name: "todo-backend"
spec:
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: "todo-backend"
    app.kubernetes.io/version: "1.0.0"
  type: "ClusterIP"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app.kubernetes.io/name: "todo-backend"
    app.kubernetes.io/version: "1.0.0"
  name: "todo-backend"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "todo-backend"
      app.kubernetes.io/version: "1.0.0"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "todo-backend"
        app.kubernetes.io/version: "1.0.0"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "WORKER_CLOUD_ID"
          value: "gcp"
        image: "quay.io/rhdevelopers/todo-backend:1.0.0"
        imagePullPolicy: "Always"
        name: "todo-backend"
        ports:
        - containerPort: 8080
          name: "http"
          protocol: "TCP"
      serviceAccount: "todo-backend"